package clidoc

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/spf13/cobra"
)

func demoTree() *cobra.Command {
	root := &cobra.Command{Use: "demo", Short: "Demo client"}
	root.PersistentFlags().String("server", "", "server base URL")
	enroll := &cobra.Command{
		Use:   "enroll",
		Short: "Enroll this device",
		Long:  "Enrolls the device with the server and stores the credential.",
		RunE:  func(*cobra.Command, []string) error { return nil },
	}
	enroll.Flags().Bool("headless", false, "enroll without a browser")
	users := &cobra.Command{Use: "users", Short: "Manage users", Long: "Manage users.\n\nEach verb acts on one user."}
	users.AddCommand(&cobra.Command{Use: "list", Short: "List users", RunE: func(*cobra.Command, []string) error { return nil }})
	hidden := &cobra.Command{Use: "drain", Short: "Hidden plumbing", Hidden: true, RunE: func(*cobra.Command, []string) error { return nil }}
	root.AddCommand(enroll, users, hidden, Command())
	return root
}

func TestWriteTree(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "website", "content", "reference", "cli", "demo")
	root := demoTree()
	root.InitDefaultCompletionCmd()
	if err := Write(root, dir); err != nil {
		t.Fatal(err)
	}
	names, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	var got []string
	for _, n := range names {
		got = append(got, n.Name())
	}
	want := "_index.md demo_enroll.md demo_users.md demo_users_list.md"
	if strings.Join(got, " ") != want {
		t.Fatalf("want pages %q, got %q (hidden, gen-docs and Cobra's completion must be absent)", want, strings.Join(got, " "))
	}
	index := read(t, filepath.Join(dir, "_index.md"))
	for _, s := range []string{
		"---\ntitle: demo\ndescription: Demo client\npagetype: reference\nweight: 1\ndraft: false\nsources:\n  - cmd/demo\nkeywords: demo\n---\n",
		"<!-- Generated by the gen-docs command of demo",
		"## Commands\n\n* [demo enroll](/reference/cli/demo/demo_enroll/): Enroll this device\n* [demo users](/reference/cli/demo/demo_users/): Manage users\n",
	} {
		if !strings.Contains(index, s) {
			t.Errorf("_index.md lacks %q:\n%s", s, index)
		}
	}
	for _, bad := range []string{"## demo\n", "SEE ALSO", "## See also", "Auto generated", "\t - ", "gen-docs DIR", "drain", "-->\n\nDemo client\n", "help for"} {
		if strings.Contains(index, bad) {
			t.Errorf("_index.md must not contain %q:\n%s", bad, index)
		}
	}
	enroll := read(t, filepath.Join(dir, "demo_enroll.md"))
	for _, s := range []string{
		"title: demo enroll\n", "weight: 2\n", "keywords: demo, enroll\n",
		"-->\n\n## Synopsis\n\nEnrolls the device with the server and stores the credential.\n\n```\ndemo enroll [flags]\n```\n\n## Options\n\n```\n",
		"--headless", "## Options inherited from parent commands\n\n```\n", "--server",
		"## See also\n\n* [demo](/reference/cli/demo/): Demo client\n",
	} {
		if !strings.Contains(enroll, s) {
			t.Errorf("demo_enroll.md lacks %q:\n%s", s, enroll)
		}
	}
	for _, bad := range []string{"### ", "Enroll this device\n\n## Synopsis", "help for"} {
		if strings.Contains(enroll, bad) {
			t.Errorf("demo_enroll.md must not contain %q (headings at level 2, the Short only in the front matter, no help line):\n%s", bad, enroll)
		}
	}
	users := read(t, filepath.Join(dir, "demo_users.md"))
	if strings.Contains(users, "Manage users.") || !strings.Contains(users, "## Synopsis\n\nEach verb acts on one user.\n") {
		t.Errorf("a Long that opens with the Short must not repeat it on the page:\n%s", users)
	}
	list := read(t, filepath.Join(dir, "demo_users_list.md"))
	if !strings.Contains(list, "title: demo users list\n") || !strings.Contains(list, "* [demo users](/reference/cli/demo/demo_users/): Manage users") {
		t.Errorf("nested page wrong:\n%s", list)
	}
	if strings.Contains(list, "## Options\n") || !strings.Contains(list, "-->\n\n```\ndemo users list [flags]\n```\n\n## Options inherited") {
		t.Errorf("a command whose only own flag is --help must have no Options section:\n%s", list)
	}
}

// TestRootWeightsFollowTheIndexOrder: the three binaries' root pages sort
// as the hand-written CLI index lists them, strazad, strazactl, straza, and
// any other root keeps weight 1.
func TestRootWeightsFollowTheIndexOrder(t *testing.T) {
	for name, want := range map[string]string{"strazad": "1", "strazactl": "2", "straza": "3", "demo": "1"} {
		dir := filepath.Join(t.TempDir(), "website", "content", "reference", "cli", name)
		root := &cobra.Command{Use: name, Short: "Root"}
		root.AddCommand(&cobra.Command{Use: "version", Short: "Print the version", RunE: func(*cobra.Command, []string) error { return nil }})
		if err := Write(root, dir); err != nil {
			t.Fatal(err)
		}
		if index := read(t, filepath.Join(dir, "_index.md")); !strings.Contains(index, "\nweight: "+want+"\n") {
			t.Errorf("%s root page wants weight %s:\n%s", name, want, index)
		}
	}
}

func TestWriteIsDeterministicAndReplacesDir(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "website", "content", "reference", "cli", "demo")
	if err := Write(demoTree(), dir); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "stale.md"), []byte("old"), 0o644); err != nil {
		t.Fatal(err)
	}
	first := read(t, filepath.Join(dir, "demo_enroll.md"))
	if err := Write(demoTree(), dir); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "stale.md")); !os.IsNotExist(err) {
		t.Error("a second run must remove pages the tree no longer has")
	}
	if second := read(t, filepath.Join(dir, "demo_enroll.md")); second != first {
		t.Errorf("two runs differ:\n%s\n---\n%s", first, second)
	}
}

func TestSitePath(t *testing.T) {
	cases := map[string]string{
		"website/content/reference/cli/straza":            "/reference/cli/straza/",
		"./website/content/reference/cli/strazactl/":      "/reference/cli/strazactl/",
		"/srv/repo/website/content/reference/cli/strazad": "/reference/cli/strazad/",
		"out/pages": "/out/pages/",
	}
	for in, want := range cases {
		if got := sitePath(in); got != want {
			t.Errorf("sitePath(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestGenDocsCommandSkipsTheRootPreRun(t *testing.T) {
	root := demoTree()
	ran := false
	root.PersistentPreRunE = func(*cobra.Command, []string) error {
		ran = true
		return nil
	}
	dir := filepath.Join(t.TempDir(), "website", "content", "reference", "cli", "demo")
	root.SetArgs([]string{"gen-docs", dir})
	if err := root.Execute(); err != nil {
		t.Fatal(err)
	}
	if ran {
		t.Error("the root PersistentPreRunE must not run for gen-docs")
	}
	if _, err := os.Stat(filepath.Join(dir, "_index.md")); err != nil {
		t.Error("gen-docs wrote nothing:", err)
	}
}

func read(t *testing.T, path string) string {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}
