package main

import (
	"fmt"
	"regexp"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// openAPIPath is where the api mode reads the document, relative to the
// repository root the Makefile runs from.
const openAPIPath = "pkg/api/openapi.yaml"

// apiDoc is the slice of the OpenAPI document the API page reads. Paths stays
// a yaml.Node so the page keeps the document's own path order.
type apiDoc struct {
	Info struct {
		Version string `yaml:"version"`
	} `yaml:"info"`
	Tags       []apiTag  `yaml:"tags"`
	Paths      yaml.Node `yaml:"paths"`
	Components struct {
		SecuritySchemes map[string]apiScheme `yaml:"securitySchemes"`
		Responses       yaml.Node            `yaml:"responses"`
		Schemas         yaml.Node            `yaml:"schemas"`
	} `yaml:"components"`
}

// apiTag is one entry of the document's tags list: the heading its
// operations render under, in list order, and the sentence beneath it.
type apiTag struct {
	Name        string `yaml:"name"`
	Description string `yaml:"description"`
}

// apiScheme is one entry of components.securitySchemes.
type apiScheme struct {
	Type        string `yaml:"type"`
	Scheme      string `yaml:"scheme"`
	Description string `yaml:"description"`
}

// apiOperation is one method on one path.
type apiOperation struct {
	Method      string
	Path        string
	OperationID string                `yaml:"operationId"`
	Summary     string                `yaml:"summary"`
	Tags        []string              `yaml:"tags"`
	Security    []map[string][]string `yaml:"security"`
	RequestBody yaml.Node             `yaml:"requestBody"`
	Responses   yaml.Node             `yaml:"responses"`
}

// apiMethods is the order methods take within one path.
var apiMethods = []string{"get", "post", "put", "patch", "delete", "head", "options"}

// noisySummaryRe finds the version numbers and decision tokens a public table
// cell may not carry.
var noisySummaryRe = regexp.MustCompile(`\b\d+\.\d+\.\d+\b|\b[DTP]\d{1,2}(?:\.\d)?\b|\bphase \d|\brev \d+|\bspec/|\bTier-\d`)

// maxCellWords is the docs style cap on a table cell.
const maxCellWords = 25

// renderAPIPage writes the API reference page from the OpenAPI document:
// front matter, a generated-file comment, the prose on what the API is and
// how a caller authenticates, the error shape, then one heading, sentence and
// table per tag in the document's tags order, with method, path, summary and
// security scheme, then the section's request bodies and answers, and at the
// end every object those tables name. It fails on a summary over the cell cap or with a version
// or decision token, on an operation whose tag is missing or undeclared, on a
// declared tag with no description or no operation, and on a document whose
// approver error codes or security schemes are missing, so the page never
// ships a cell outside the docs style or a route under no heading.
func renderAPIPage(document []byte) (string, error) {
	var doc apiDoc
	if err := yaml.Unmarshal(document, &doc); err != nil {
		return "", fmt.Errorf("parse %s: %w", openAPIPath, err)
	}
	ops, err := apiOperations(doc.Paths)
	if err != nil {
		return "", err
	}
	if len(ops) == 0 {
		return "", fmt.Errorf("%s declares no operations", openAPIPath)
	}
	if len(doc.Components.SecuritySchemes) == 0 {
		return "", fmt.Errorf("%s declares no security scheme under components.securitySchemes", openAPIPath)
	}
	approverError := mapGet(&doc.Components.Responses, "ApproverError")
	codes := seqValues(mapGet(mapGet(mapGet(mapGet(mapGet(mapGet(approverError, "content"), "application/json"), "schema"), "properties"), "code"), "enum"))
	if len(codes) == 0 {
		return "", fmt.Errorf("%s has no code enum under components.responses.ApproverError", openAPIPath)
	}
	sections, err := groupAPIOperations(doc.Tags, ops)
	if err != nil {
		return "", err
	}
	paths := map[string]bool{}
	for _, op := range ops {
		paths[op.Path] = true
	}
	sh := newShapes(&doc)
	var b strings.Builder
	b.WriteString(`---
title: API
description: Every operation of the strazad HTTP API by method and path, with its summary, the credential it takes, its request body, its answers and the objects they carry, from the OpenAPI document.
pagetype: reference
weight: 30
draft: false
sources:
  - pkg/api/openapi.yaml
  - internal/server/server.go
  - internal/server/admin_common.go
  - internal/server/api_approvals.go
  - internal/server/api_connect.go
  - internal/server/approver_common.go
keywords: api http openapi endpoints
---
<!-- Generated by tools/docsgen from pkg/api/openapi.yaml.
     Do not edit this file; edit the document and run make docs-gen. -->

<!-- source: pkg/api/openapi.yaml info; internal/server/openapi_test.go 16; internal/server/openapi_infra_test.go 26 -->
`)
	fmt.Fprintf(&b, "The strazad HTTP API is the REST surface of the server, and every tool that talks to strazad speaks it: strazactl, the console, the self-service page, the Straza approver app and the straza client. Its contract is the OpenAPI 3.1 document `pkg/api/openapi.yaml` in the repository, at version %s, and two tests in the server package fail the build when the route table and the document diverge. This page lists every operation the document declares, %d operations on %d paths, and `make docs-gen` rewrites it from the document.\n\n", doc.Info.Version, len(ops), len(paths))
	b.WriteString(`<!-- source: internal/config/config.go 84; internal/server/server.go 349-384 -->
Paths are relative to the server's public URL, so on a standalone server with its default listener the users list is ` + "`http://127.0.0.1:8420/v1/admin/users`" + `. Every request and answer body is JSON. On the same listener, outside this document, sit the MCP gateway at ` + "`/mcp`" + `, the SCIM 2.0 endpoint whose contract is the SCIM profile specification, the console under ` + "`/console/`" + `, the self-service page under ` + "`/approvals/`" + `, the metrics endpoint at ` + "`/metrics`" + ` and the built-in issuer under ` + "`/oidc/`" + `, which serves the full device flow in the standalone profile and only the client credentials grant with its discovery document in the enterprise profile, so an AI agent can authenticate at Straza itself.

## Authentication

<!-- source: pkg/api/openapi.yaml components.securitySchemes and the security field of each operation -->
`)
	b.WriteString(securityProse(doc.Components.SecuritySchemes, ops))
	b.WriteString(`
<!-- source: internal/server/server.go 187-320; internal/server/admin_common.go 47-160; internal/server/api_connect.go 50-62; internal/server/api_approvals.go 70-101; internal/server/approver_common.go 70-100; internal/server/pdp.go 51-56; internal/server/api_audit.go 164-165; internal/server/push.go 106; internal/server/api_policy.go 504-569 -->
Which token a bearer route takes depends on the route, and the scheme each operation declares names its lane. The admin routes under ` + "`/v1/admin/`" + ` take a session token or a console login token whose user holds the ` + "`straza-admin`" + ` role or a role mapped to admin areas, or an admin API token (prefix ` + "`wat_`" + `) whose scope covers the area, and refuse everything else with 401 or 403 and a sentence naming the missing scope. ` + "`/v1/decide`, `/v1/audit/batch`, `/v1/push` and `/v1/session/revoke`" + ` take the session token a client received at check-in, and that token names the only session they act on. ` + "`/v1/audit/batch`" + ` also files a record under an earlier session its record names, when that session belongs to the same user on the same device. ` + "`/v1/snapshot`" + ` takes the same token in the enterprise profile and answers without one in the standalone profile. ` + "`/v1/connect`, `/v1/self`, `/v1/approvals/self/enroll-token`" + ` and the approve and deny routes under ` + "`/v1/admin/approvals/`" + ` take any active user's session or login token and refuse an admin API token, and the handler checks the approver roles itself. The ` + "`/v1/approver/`" + ` routes take the approver device token a phone receives at enrollment and refuse every other token kind. An operation that declares no scheme is either public by design (the probes, the discovery documents and the harness config, none of which carries a secret) or carries its credential inside the request: the enroll and check-in bodies, the one-time enroll token of the approver enrollment, the device-key signature over a refresh challenge, and the Slack signature header on the Slack callback.

## Errors

<!-- source: pkg/api/openapi.yaml components.responses.Error, components.responses.ServiceUnavailable and components.responses.ApproverError -->
An error answer is a JSON object whose ` + "`error`" + ` field is a sentence that says what failed, and on a 5xx or a recovered panic the object also carries ` + "`correlation_id`" + `, the value of the ` + "`X-Request-Id`" + ` response header and of the matching server log record. Every answer carries ` + "`X-Request-Id`" + `. A client-supplied id of at most 64 printable ASCII bytes is echoed, and anything else is replaced by a minted UUIDv7. When the server cannot reach its store while checking a credential it answers 503 with a ` + "`Retry-After`" + ` header and a generic body, which tells the client to retry and never to drop a credential. `)
	fmt.Fprintf(&b, "The approver surface adds a `code` field the phone app branches on before it touches its hardware key, one of %s.\n", codeList(codes))
	for _, s := range sections {
		fmt.Fprintf(&b, "\n## %s {#api-%s}\n\n%s\n\n| Method | Path | Summary | Security |\n|---|---|---|---|\n", s.tag.Name, slug(s.tag.Name), s.tag.Description)
		for _, op := range s.ops {
			cell, err := summaryCell(op)
			if err != nil {
				return "", err
			}
			fmt.Fprintf(&b, "| %s | `%s` | %s | %s |\n", strings.ToUpper(op.Method), op.Path, cell, securityCell(op))
		}
		if err := sh.writeShapeTables(&b, s.ops); err != nil {
			return "", err
		}
	}
	if err := sh.writeObjects(&b); err != nil {
		return "", err
	}
	return b.String(), nil
}

// apiOperations walks the paths mapping in document order and returns every
// operation, methods in apiMethods order within a path. Path-level keys that
// are not methods, such as parameters, are skipped.
func apiOperations(paths yaml.Node) ([]apiOperation, error) {
	if paths.Kind != yaml.MappingNode {
		return nil, fmt.Errorf("%s: paths is not a mapping", openAPIPath)
	}
	var ops []apiOperation
	for i := 0; i+1 < len(paths.Content); i += 2 {
		path := paths.Content[i].Value
		item := paths.Content[i+1]
		if item.Kind != yaml.MappingNode {
			return nil, fmt.Errorf("%s: path %s is not a mapping", openAPIPath, path)
		}
		byMethod := map[string]*yaml.Node{}
		for j := 0; j+1 < len(item.Content); j += 2 {
			byMethod[item.Content[j].Value] = item.Content[j+1]
		}
		for _, m := range apiMethods {
			node, ok := byMethod[m]
			if !ok {
				continue
			}
			op := apiOperation{Method: m, Path: path}
			if err := node.Decode(&op); err != nil {
				return nil, fmt.Errorf("%s: %s %s: %w", openAPIPath, strings.ToUpper(m), path, err)
			}
			ops = append(ops, op)
		}
	}
	return ops, nil
}

// renderedSection is one heading of the page with its operations in order.
type renderedSection struct {
	tag apiTag
	ops []apiOperation
}

// groupAPIOperations places every operation under its first tag, sections in
// the order of the document's tags list. It refuses an operation with no tag
// or with a tag the list does not declare, a tag with no description, and a
// declared tag no operation uses, so the list and the routes cannot drift.
func groupAPIOperations(tags []apiTag, ops []apiOperation) ([]renderedSection, error) {
	if len(tags) == 0 {
		return nil, fmt.Errorf("%s declares no top-level tags list", openAPIPath)
	}
	sections := make([]renderedSection, len(tags))
	index := map[string]int{}
	for i, t := range tags {
		if strings.TrimSpace(t.Description) == "" {
			return nil, fmt.Errorf("%s: tag %q has no description, add one sentence", openAPIPath, t.Name)
		}
		if _, dup := index[t.Name]; dup {
			return nil, fmt.Errorf("%s: tag %q is listed twice", openAPIPath, t.Name)
		}
		index[t.Name] = i
		sections[i].tag = t
	}
	for _, op := range ops {
		who := strings.ToUpper(op.Method) + " " + op.Path
		if len(op.Tags) == 0 {
			return nil, fmt.Errorf("%s: %s carries no tag, add one from the document's tags list", openAPIPath, who)
		}
		i, ok := index[op.Tags[0]]
		if !ok {
			return nil, fmt.Errorf("%s: %s carries the tag %q, which the document's tags list does not declare", openAPIPath, who, op.Tags[0])
		}
		sections[i].ops = append(sections[i].ops, op)
	}
	for _, s := range sections {
		if len(s.ops) == 0 {
			return nil, fmt.Errorf("%s: tag %q has no operation, drop it from the tags list", openAPIPath, s.tag.Name)
		}
	}
	return sections, nil
}

// slug turns a tag into a heading anchor: lower case, one hyphen for each
// run of other characters.
func slug(tag string) string {
	var b strings.Builder
	dash := false
	for _, r := range strings.ToLower(tag) {
		if r >= 'a' && r <= 'z' || r >= '0' && r <= '9' {
			b.WriteRune(r)
			dash = false
		} else if !dash {
			b.WriteRune('-')
			dash = true
		}
	}
	return strings.Trim(b.String(), "-")
}

// summaryCell returns the Summary cell, the document's summary with pipes
// escaped. It refuses an empty summary and one that runs over maxCellWords
// or matches noisySummaryRe, so the fix lands in the document.
func summaryCell(op apiOperation) (string, error) {
	who := strings.ToUpper(op.Method) + " " + op.Path
	cell := strings.TrimSpace(op.Summary)
	if cell == "" {
		return "", fmt.Errorf("%s has no summary in %s", who, openAPIPath)
	}
	if len(strings.Fields(cell)) > maxCellWords || noisySummaryRe.MatchString(cell) {
		return "", fmt.Errorf("%s: the summary in %s is over %d words or carries a version or decision token, shorten it to one plain sentence", who, openAPIPath, maxCellWords)
	}
	return strings.ReplaceAll(cell, "|", "\\|"), nil
}

// securityCell names the schemes an operation declares, or none.
func securityCell(op apiOperation) string {
	var names []string
	for _, req := range op.Security {
		for name := range req {
			names = append(names, "`"+name+"`")
		}
	}
	if len(names) == 0 {
		return "none"
	}
	sort.Strings(names)
	return strings.Join(names, " or ")
}

// securityProse states each declared scheme with the document's description,
// how many operations declare it, and which operations declare none.
func securityProse(schemes map[string]apiScheme, ops []apiOperation) string {
	names := make([]string, 0, len(schemes))
	for name := range schemes {
		names = append(names, name)
	}
	sort.Strings(names)
	var b strings.Builder
	if len(names) == 1 {
		b.WriteString("The document declares one security scheme. ")
	} else {
		fmt.Fprintf(&b, "The document declares %d security schemes. ", len(names))
	}
	for i, name := range names {
		s := schemes[name]
		count := 0
		for _, op := range ops {
			for _, req := range op.Security {
				if _, ok := req[name]; ok {
					count++
					break
				}
			}
		}
		desc := strings.TrimSuffix(strings.TrimSpace(s.Description), ".")
		// Two sentence shapes alternate so a document with several schemes
		// does not open three sentences in a row the same way.
		if i%2 == 0 {
			fmt.Fprintf(&b, "`%s` is an %s %s token, described in the document as \"%s\", and %d of the %d operations declare it. ", name, strings.ToUpper(s.Type), s.Scheme, desc, count, len(ops))
		} else {
			fmt.Fprintf(&b, "%d of the %d operations declare `%s`, an %s %s token described in the document as \"%s\". ", count, len(ops), name, strings.ToUpper(s.Type), s.Scheme, desc)
		}
	}
	var open []string
	for _, op := range ops {
		if len(op.Security) == 0 {
			open = append(open, "`"+strings.ToUpper(op.Method)+" "+op.Path+"`")
		}
	}
	switch len(open) {
	case 0:
		b.WriteString("Every operation declares a scheme.\n")
	case 1:
		fmt.Fprintf(&b, "One operation declares none, %s, and its table below says `none` in the last column.\n", open[0])
	default:
		fmt.Fprintf(&b, "The %d operations that declare none are %s and %s, and their tables below say `none` in the last column.\n", len(open), strings.Join(open[:len(open)-1], ", "), open[len(open)-1])
	}
	return b.String()
}

// codeList renders an enum as a backticked series.
func codeList(codes []string) string {
	quoted := make([]string, len(codes))
	for i, c := range codes {
		quoted[i] = "`" + c + "`"
	}
	if len(quoted) == 1 {
		return quoted[0]
	}
	return strings.Join(quoted[:len(quoted)-1], ", ") + " or " + quoted[len(quoted)-1]
}
