package main

import (
	"os"
	"regexp"
	"strings"
	"testing"
)

// apiFixture is a small OpenAPI document: a tags list whose order differs
// from the paths order, a path whose methods appear out of order, an
// operation without a scheme, and one scheme.
const apiFixture = `openapi: "3.1.0"
info:
  title: Fixture
  version: 9.9.9
tags:
  - name: Health
    description: The probes.
  - name: Widgets
    description: Widgets and the gadgets they hold.
paths:
  /v1/admin/widgets:
    post:
      operationId: createWidget
      summary: Create a widget
      tags: [Widgets]
      security: [{ bearer: [] }]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name]
              properties:
                name:
                  type: string
                  description: The widget's name.
                size:
                  type: string
                  enum: [small, large]
                  description: How big it is.
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Widget" }
        "409":
          $ref: "#/components/responses/Error"
    get:
      operationId: listWidgets
      summary: List widgets
      tags: [Widgets]
      security: [{ bearer: [] }]
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items: { $ref: "#/components/schemas/Widget" }
  /v1/admin/widgets/{id}/doc:
    put:
      operationId: putWidgetDoc
      summary: Replace a widget document
      tags: [Widgets]
      security: [{ bearer: [] }]
      requestBody:
        required: true
        description: A widget document in YAML.
        content:
          application/yaml:
            schema: { type: string }
      responses:
        "204":
          description: Replaced
  /healthz:
    get:
      operationId: healthz
      summary: Liveness probe
      tags: [Health]
  /v1/admin/gadgets/{id}:
    delete:
      operationId: deleteGadget
      summary: Delete a gadget
      tags: [Widgets]
      security: [{ bearer: [] }]
      responses:
        "200":
          description: Deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  id: { type: string }
                  status: { type: string }
components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      description: A session token.
  schemas:
    Widget:
      type: object
      description: A widget.
      properties:
        id: { type: string }
        name:
          type: string
          description: The widget's name.
        gadgets:
          type: array
          items: { $ref: "#/components/schemas/Gadget" }
    Gadget:
      type: object
      properties:
        kind:
          type: string
          enum: [lever, dial]
  responses:
    Error:
      description: An error with the reason in a sentence.
      content:
        application/json:
          schema:
            type: object
            properties:
              error: { type: string }
    ApproverError:
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: string
                enum: [missing_token, token_expired]
`

func TestRenderAPIPage(t *testing.T) {
	got, err := renderAPIPage([]byte(apiFixture))
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		"---\ntitle: API\n",
		"pagetype: reference\n",
		"weight: 30\n",
		"sources:\n  - pkg/api/openapi.yaml\n",
		"<!-- Generated by tools/docsgen from pkg/api/openapi.yaml.",
		"at version 9.9.9, ",
		"5 operations on 4 paths",
		"The document declares one security scheme. `bearer` is an HTTP bearer token, described in the document as \"A session token\", and 4 of the 5 operations declare it. One operation declares none, `GET /healthz`,",
		"one of `missing_token` or `token_expired`.",
		"## Health {#api-health}\n\nThe probes.\n\n| Method | Path | Summary | Security |\n|---|---|---|---|\n| GET | `/healthz` | Liveness probe | none |\n",
		"## Widgets {#api-widgets}\n\nWidgets and the gadgets they hold.\n\n| Method | Path | Summary | Security |\n|---|---|---|---|\n| GET | `/v1/admin/widgets` | List widgets | `bearer` |\n| POST | `/v1/admin/widgets` | Create a widget | `bearer` |\n| PUT | `/v1/admin/widgets/{id}/doc` | Replace a widget document | `bearer` |\n| DELETE | `/v1/admin/gadgets/{id}` | Delete a gadget | `bearer` |\n",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("rendered page lacks %q:\n%s", want, got)
		}
	}
	if strings.Index(got, "## Health") > strings.Index(got, "## Widgets") {
		t.Error("sections must follow the document's tags order, not the paths order")
	}
	again, err := renderAPIPage([]byte(apiFixture))
	if err != nil || again != got {
		t.Error("rendering is not deterministic")
	}
}

func TestRenderAPIShapes(t *testing.T) {
	got, err := renderAPIPage([]byte(apiFixture))
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		"Request bodies in this section, one row per field.\n\n| Operation | Field | Type | Required | Meaning |\n|---|---|---|---|---|\n",
		"| `POST /v1/admin/widgets` | `name` | string | yes | The widget's name. |\n",
		"| `POST /v1/admin/widgets` | `size` | string |  | How big it is. One of `small` or `large`. |\n",
		"| `PUT /v1/admin/widgets/{id}/doc` | `the document` | application/yaml | yes | A widget document in YAML. |\n",
		"Answers in this section, by status.\n\n| Operation | Status | Answer |\n|---|---|---|\n",
		"| `GET /v1/admin/widgets` | 200 | a list of `Widget` |\n",
		"| `POST /v1/admin/widgets` | 201 | `Widget` |\n| `POST /v1/admin/widgets` | 409 | `Error` |\n",
		"| `PUT /v1/admin/widgets/{id}/doc` | 204 | an empty body |\n",
		"| `DELETE /v1/admin/gadgets/{id}` | 200 | an object with `id` and `status` |\n",
		"## Objects {#api-objects}\n\nEvery object the tables above name, in the order they first name it, with its fields. A row without a field carries the object's own meaning.\n\n| Object | Field | Type | Meaning |\n|---|---|---|---|\n",
		"| `Widget` | | | A widget. |\n| `Widget` | `id` | string |  |\n| `Widget` | `name` | string | The widget's name. |\n| `Widget` | `gadgets` | list of `Gadget` |  |\n",
		"| `Error` | | | An error with the reason in a sentence. |\n| `Error` | `error` | string |  |\n",
		"| `Gadget` | `kind` | string | One of `lever` or `dial`. |\n",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("rendered page lacks %q:\n%s", want, got)
		}
	}
	if strings.Index(got, "| `Widget` |") > strings.Index(got, "| `Error` |") || strings.Index(got, "| `Error` |") > strings.Index(got, "| `Gadget` |") {
		t.Error("objects must appear in first-reference order: Widget, Error, then Gadget")
	}
	if strings.Contains(got, "## Health {#api-health}\n\nThe probes.\n\n| Method | Path | Summary | Security |\n|---|---|---|---|\n| GET | `/healthz` | Liveness probe | none |\n\nRequest bodies") {
		t.Error("a section without a request body must not get a request bodies table")
	}
}

func TestRenderAPIPageRefusals(t *testing.T) {
	replace := func(old, new string) func(string) string {
		return func(s string) string { return strings.Replace(s, old, new, 1) }
	}
	cases := []struct {
		name string
		edit func(string) string
		want string
	}{
		{"long summary", replace("summary: Liveness probe", "summary: "+strings.Repeat("word ", 26)), "GET /healthz: the summary in pkg/api/openapi.yaml is over 25 words or carries a version or decision token, shorten it"},
		{"decision token", replace("summary: Liveness probe", "summary: Liveness probe (D12)"), "GET /healthz: the summary in pkg/api/openapi.yaml is over 25 words or carries a version or decision token"},
		{"version token", replace("summary: List widgets", "summary: List widgets (0.58.0)"), "GET /v1/admin/widgets: the summary"},
		{"empty summary", replace("summary: Liveness probe", "summary: \"\""), "GET /healthz has no summary"},
		{"no tags list", replace("tags:\n  - name: Health\n    description: The probes.\n  - name: Widgets\n    description: Widgets and the gadgets they hold.\n", ""), "declares no top-level tags list"},
		{"untagged operation", replace("      tags: [Health]\n", ""), "GET /healthz carries no tag, add one from the document's tags list"},
		{"undeclared tag", replace("tags: [Health]", "tags: [Probes]"), `GET /healthz carries the tag "Probes", which the document's tags list does not declare`},
		{"tag without description", replace("    description: The probes.\n", ""), `tag "Health" has no description`},
		{"tag listed twice", replace("  - name: Widgets\n", "  - name: Health\n    description: Again.\n  - name: Widgets\n"), `tag "Health" is listed twice`},
		{"unused tag", replace("  - name: Widgets\n", "  - name: Gizmos\n    description: Nothing uses it.\n  - name: Widgets\n"), `tag "Gizmos" has no operation, drop it`},
		{"no security scheme", replace("  securitySchemes:\n    bearer:\n      type: http\n      scheme: bearer\n      description: A session token.\n", ""), "declares no security scheme"},
		{"no approver codes", replace("enum: [missing_token, token_expired]", "enum: []"), "no code enum under components.responses.ApproverError"},
		{"noisy field description", replace("description: The widget's name.\n                size:", "description: The widget's name (0.58.0).\n                size:"), "POST /v1/admin/widgets field name: the description's first sentence in pkg/api/openapi.yaml is over 25 words or carries a version or decision token"},
		{"long field description", replace("description: How big it is.", "description: "+strings.Repeat("word ", 26)+"."), "POST /v1/admin/widgets field size: the description's first sentence"},
		{"document body without description", replace("        description: A widget document in YAML.\n", ""), "PUT /v1/admin/widgets/{id}/doc: the application/yaml request body in pkg/api/openapi.yaml needs a description sentence"},
		{"dangling reference", replace(`schema: { $ref: "#/components/schemas/Widget" }`, `schema: { $ref: "#/components/schemas/Gizmo" }`), `reference "#/components/schemas/Gizmo" points at nothing in components`},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := renderAPIPage([]byte(tc.edit(apiFixture)))
			if err == nil || !strings.Contains(err.Error(), tc.want) {
				t.Fatalf("want error containing %q, got %v", tc.want, err)
			}
		})
	}
}

func TestSlug(t *testing.T) {
	for _, tc := range []struct{ tag, want string }{
		{"Approvals", "approvals"},
		{"Health and discovery", "health-and-discovery"},
		{"Roles, assignments and knowledge packs", "roles-assignments-and-knowledge-packs"},
		{"PolicySets", "policysets"},
		{" Admin API tokens ", "admin-api-tokens"},
	} {
		if got := slug(tc.tag); got != tc.want {
			t.Errorf("slug(%q) = %q, want %q", tc.tag, got, tc.want)
		}
	}
}

// internalTokenRe matches the internal reference tokens a table row may not
// carry, so the shipped document can never leak a decision token into the
// generated table.
var internalTokenRe = regexp.MustCompile(`\((?:[DTKEPFM]\d{1,3}(?:\.\d+)?|[PQBCES]-\d{3})\b\)?|\b\d+\.\d+\.\d+\b|\bphase \d|\brev \d+`)

// TestRealDocumentRenders pins the shipped document: every operation tagged
// and placed, every summary inside the cell cap and free of version tokens,
// so make docs-gen cannot fail on the real input and the table carries no
// dash or internal token.
func TestRealDocumentRenders(t *testing.T) {
	document, err := os.ReadFile("../../" + openAPIPath)
	if err != nil {
		t.Fatal(err)
	}
	got, err := renderAPIPage(document)
	if err != nil {
		t.Fatal(err)
	}
	if strings.ContainsAny(got, "\u2014\u2013") {
		t.Error("the rendered page carries an em or en dash; fix the summary or the tag description")
	}
	for _, line := range strings.Split(got, "\n") {
		if !strings.HasPrefix(line, "| ") {
			continue
		}
		if m := internalTokenRe.FindString(line); m != "" {
			t.Errorf("table row carries the internal token %q: %s", m, line)
		}
		for _, cell := range strings.Split(strings.Trim(line, "|"), "|") {
			if n := len(strings.Fields(cell)); n > maxCellWords {
				t.Errorf("table cell of %d words is over %d: %s", n, maxCellWords, strings.TrimSpace(cell))
			}
		}
	}
}
