package main

import (
	"strings"
	"testing"

	"github.com/strazahq/straza/internal/config"
)

func TestRenderConfigPage(t *testing.T) {
	knobs := []config.Knob{
		{Path: "profile", Env: "STRAZA_PROFILE", EnvSpecial: "resolveProfile", Doc: "core"},
		{Path: "oauth.providers.github.clientId", Env: "STRAZA_OAUTH_GITHUB_CLIENT_ID", EnvSpecial: "map", Doc: "core", Note: "The client id."},
		{Path: "server.listen", Env: "STRAZA_LISTEN", Doc: "server"},
		{Path: "server.maxBodyBytes", NoEnvReason: "tuning knob, file-only by decision", Doc: "server"},
		{Path: "approval.push.relay.url", Env: "STRAZA_APPROVAL_PUSH_RELAY_URL", Doc: "server", Note: "The relay to send through; empty means the official one."},
		{Path: "sinks", NoEnvReason: "list of sinks", Doc: "server", Note: "The audit sinks."},
	}
	sections := []config.KnobSection{{ID: "core", Title: "Core"}, {ID: "server", Title: "Server"}}
	got, err := renderConfigPage(knobs, sections)
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		"---\ntitle: Configuration\n",
		"pagetype: reference\n",
		"sources:\n  - internal/config/knobs.go\n",
		"<!-- Generated by tools/docsgen",
		"Every key of `straza.yaml` is one row below, with the environment variable that sets it when there is one. A map or a list is one row, and its note says what each entry holds.",
		"## Core {#core}\n\n| Key | Environment | Notes |\n|---|---|---|\n| `profile` | `STRAZA_PROFILE` | Read before any other key, so it decides the defaults every other key starts from. |\n",
		"| `oauth.providers.github.clientId` | `STRAZA_OAUTH_GITHUB_CLIENT_ID` | The client id. Sets this key of the github provider, so no config file is needed. |\n",
		"## Server {#server}\n",
		"| `server.listen` | `STRAZA_LISTEN` |  |\n",
		"| `server.maxBodyBytes` | none | tuning knob, file-only by decision |\n",
		"| `approval.push.relay.url` | `STRAZA_APPROVAL_PUSH_RELAY_URL` | The relay to send through; empty means the official one. |\n",
		"| `sinks` | none | The audit sinks. list of sinks |\n",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("rendered page lacks %q:\n%s", want, got)
		}
	}
	if strings.Index(got, "## Core") > strings.Index(got, "## Server") {
		t.Error("sections must follow the KnobSections order")
	}
	again, err := renderConfigPage(knobs, sections)
	if err != nil || again != got {
		t.Error("rendering is not deterministic")
	}
}

func TestRenderConfigPageRefusals(t *testing.T) {
	sections := []config.KnobSection{{ID: "core", Title: "Core"}}
	cases := []struct {
		name string
		knob config.Knob
		want string
	}{
		{"unlisted section", config.Knob{Path: "x", Env: "X", Doc: "nowhere"}, "which KnobSections does not list"},
		{"unknown special", config.Knob{Path: "x", Env: "X", EnvSpecial: "magic", Doc: "core"}, "no note in tools/docsgen/render.go"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := renderConfigPage([]config.Knob{tc.knob}, sections)
			if err == nil || !strings.Contains(err.Error(), tc.want) {
				t.Fatalf("want error containing %q, got %v", tc.want, err)
			}
		})
	}
}

// TestRealTableRenders pins the shipped table: every section listed, every
// special marker noted, so make docs-gen cannot fail on the real input.
func TestRealTableRenders(t *testing.T) {
	got, err := renderConfigPage(config.Knobs(), config.KnobSections())
	if err != nil {
		t.Fatal(err)
	}
	if strings.ContainsAny(got, "\u2014\u2013") {
		t.Error("the rendered page carries an em or en dash; fix the knob string")
	}
}
