package main

import (
	"fmt"
	"strings"

	"github.com/strazahq/straza/internal/config"
)

// specialNotes turns the EnvSpecial marker of a knob into the plain sentence
// the configuration page shows about its environment variable.
var specialNotes = map[string]string{
	"resolveProfile": "Read before any other key, so it decides the defaults every other key starts from.",
	"map":            "Sets this key of the github provider, so no config file is needed.",
}

// renderConfigPage writes the configuration reference page for the knob
// table: front matter, a generated-file comment, one sentence on where the
// table comes from, then one heading and table per section. It fails on a
// knob whose section is not listed or whose EnvSpecial has no note, so the
// page never ships a knob under no heading or a marker in place of a note.
func renderConfigPage(knobs []config.Knob, sections []config.KnobSection) (string, error) {
	var b strings.Builder
	b.WriteString(`---
title: Configuration
description: Every strazad configuration key, its environment variable when it has one, and the reason when it has none.
pagetype: reference
weight: 20
draft: false
sources:
  - internal/config/knobs.go
keywords: configuration, straza.yaml, environment variables, strazad, knobs
---
<!-- Generated by tools/docsgen from the knob table in internal/config/knobs.go.
     Do not edit this file; edit the table and run make docs-gen. -->

Every key of ` + "`straza.yaml`" + ` is one row below, with the environment variable that sets it when there is one. A map or a list is one row, and its note says what each entry holds. The rows come from the knob table in the strazad source, and ` + "`make docs-gen`" + ` rewrites this page from it.
`)
	bySection := map[string][]config.Knob{}
	for _, k := range knobs {
		bySection[k.Doc] = append(bySection[k.Doc], k)
	}
	listed := map[string]bool{}
	for _, s := range sections {
		listed[s.ID] = true
		fmt.Fprintf(&b, "\n## %s {#%s}\n\n| Key | Environment | Notes |\n|---|---|---|\n", s.Title, s.ID)
		for _, k := range bySection[s.ID] {
			note, err := knobNote(k)
			if err != nil {
				return "", err
			}
			env := "none"
			if k.Env != "" {
				env = "`" + k.Env + "`"
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s |\n", k.Path, env, note)
		}
	}
	for _, k := range knobs {
		if !listed[k.Doc] {
			return "", fmt.Errorf("knob %s names section %q, which KnobSections does not list", k.Path, k.Doc)
		}
	}
	return b.String(), nil
}

// knobNote returns the Notes cell: the knob's own Note, then the sentence
// that explains the Environment cell beside it, which is the EnvSpecial
// note when the knob has one and the reason it has no variable otherwise.
func knobNote(k config.Knob) (string, error) {
	env := k.NoEnvReason
	if k.EnvSpecial != "" {
		note, ok := specialNotes[k.EnvSpecial]
		if !ok {
			return "", fmt.Errorf("knob %s has EnvSpecial %q with no note in tools/docsgen/render.go", k.Path, k.EnvSpecial)
		}
		env = note
	}
	note := strings.TrimSpace(k.Note + " " + env)
	return strings.ReplaceAll(note, "|", "\\|"), nil
}
